version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    ports:
      - '53159:80'
    container_name: wxcloud_weixinmini
    labels:
      - wxPort=27082
      - hostPort=53159
      - wxcloud=weixinmini
      - role=container
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=FYJbREa3
      - MYSQL_ADDRESS=sh-cynosdbmysql-grp-rjrb1zmc.sql.tencentcdb.com:29957
networks:
  default:
    external:
      name: wxcb0
